apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: k8s.io/minikube-hostpath
parameters:
  server: 192.168.56.102
  path: /mnt/nfs_shared
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: 
  - hard
  - nfsvers=4.1